apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-monitor-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sumitNITS/ArgoCD-Monitor-System.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitor-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true